source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'YBRequest_Example' do
  pod 'YBRequest', :path => '../'

  target 'YBRequest_Tests' do
    inherit! :search_paths

    
  end
end
