source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '10.0'

target 'YBRequest_Example' do
  pod 'YBRequest', :path => '../'
  pod 'Aspect', '~> 1.3.5'
  pod 'AFNetworking', '~> 4.0.1'


  target 'YBRequest_Tests' do
    inherit! :search_paths

    
  end
end
